module.exports = {
    PHONEPE_BASE_URL: process.env.PHONEPE_BASE_URL,
    PHONEPE_MERCHANT_ID: process.env.PHONEPE_MERCHANT_ID,
    PHONEPE_MERCHANT_KEY: process.env.PHONEPE_MERCHANT_KEY,
    PHONEPE_SALT_KEY: process.env.PHONEPE_SALT_KEY,
    FRONTEND_URL: process.env.FRONTEND_URL,
    BACKEND_URL: process.env.BACKEND_URL
};
